
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: db
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>   
  timeout: 5000

development:
  <<: *default
  database: db/development.postgresql

test:
  <<: *default
  database: db/test.postgresql

production:
   <<: *default
   database: tmmanager
   username: yumaasato
   password: request.env['DB_PASSWORD'] # 任意のパスワード
   adapter: postgresql
   encoding: unicode
   pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# インデントは必ず半角スペース２つ